# Generated by Django 5.0.3 on 2024-04-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_auto_20221214_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='comments',
        ),
        migrations.AddField(
            model_name='product',
            name='product_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
