# Generated by Django 5.0.3 on 2024-04-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_remove_invoice_comments_product_product_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_stock',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_unit',
            field=models.IntegerField(),
        ),
    ]
