# Generated by Django 5.0.3 on 2024-04-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_remove_product_product_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_unit',
            field=models.IntegerField(default=0),
        ),
    ]
